# Generated by Django 4.2.7 on 2023-11-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("client", "0003_alter_client_client_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="groups",
            field=models.ManyToManyField(
                related_name="%(class)s_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="%(class)s_permissions", to="auth.permission"
            ),
        ),
    ]
