# Generated by Django 4.2.7 on 2023-12-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_clientmesaj_eslesme_trainermesaj_alter_client_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_hedef',
            field=models.CharField(choices=[('kilo_alma', 'Kilo Alma'), ('kilo_verme', 'Kilo Verme'), ('kilo_koruma', 'Kilo Koruma'), ('kas_kazanma', 'Kas Kazanma')], default='kilo_kazanma', max_length=20),
        ),
    ]
