# Generated by Django 4.2.7 on 2023-12-01 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_alter_trainer_trainer_kont'),
        ('client', '0008_client_client_hedef'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assigned_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.trainer', unique=True),
        ),
    ]
