# Generated by Django 4.2.7 on 2023-12-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_alter_trainer_trainer_kont'),
        ('client', '0012_beslenmeplani_tarih_egzersizplani_gonderilen_tarih'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='assigned_trainer',
        ),
        migrations.AddField(
            model_name='client',
            name='assigned_trainer',
            field=models.ManyToManyField(blank=True, null=True, to='trainer.trainer'),
        ),
    ]
