# Generated by Django 4.2.7 on 2023-11-27 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yonetici", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yonetici",
            old_name="client_email",
            new_name="yonetici_email",
        ),
    ]
