# Generated by Django 4.2.7 on 2023-11-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonetici', '0003_yoneticiprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yonetici',
            options={},
        ),
        migrations.AlterModelManagers(
            name='yonetici',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='yonetici',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='yonetici',
            name='email',
        ),
        migrations.RemoveField(
            model_name='yonetici',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='yonetici',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='yonetici',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='yonetici',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='yonetici',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='yonetici',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='yonetici',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='yonetici',
            name='password',
        ),
        migrations.RemoveField(
            model_name='yonetici',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='YoneticiProfile',
        ),
    ]
