# Generated by Django 4.2.7 on 2023-11-29 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonetici', '0004_alter_yonetici_options_alter_yonetici_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yonetici',
        ),
    ]
