# Generated by Django 4.2.7 on 2023-11-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0002_trainerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="trainer_kont",
            field=models.IntegerField(default=5),
        ),
    ]
