# Generated by Django 4.2.7 on 2023-11-28 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_trainer_trainer_kont'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={},
        ),
        migrations.AlterModelManagers(
            name='trainer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='username',
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_birthdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='TrainerProfile',
        ),
    ]
