# Generated by Django 4.2.7 on 2023-11-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('trainer', '0004_alter_trainer_options_alter_trainer_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='groups',
            field=models.ManyToManyField(related_name='trainer_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_password',
            field=models.CharField(default='123456', max_length=128),
        ),
        migrations.AddField(
            model_name='trainer',
            name='user_permissions',
            field=models.ManyToManyField(related_name='trainer_permissions', to='auth.permission'),
        ),
    ]
